### ISSUE TITLE
[Request] Is it also possible to give the same ability to the Artisan's Bench?

### ISSUE THREAD

**Issue by TA2DF** [kernelENREK/PoE_colorBlind#2]
First of all, It is a work that is worthy of commendation...
Thank you very much for your gentle efforts where considering of us.

**Comment by kernelENREK** [comment]
Ey Exile.
I suppose you mean **Vorici's** workbench. It's a really cool idea to add the same behaviour (manual and automatic) if you are using Vorici's bench.

I will try to add it on the next release.

**Comment by kernelENREK** [comment]
Feature added in commit: https://github.com/kernelENREK/PoE_colorBlind/commit/56847a7e4966f9904758c0076aff90969975ab61
